name: Build and Push Separate Images for PC and Raspberry

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract Tag
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Build and push AMD64 (PC) image
      - name: Build and Push PC (AMD64) Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: rafaelprimeiro/pz-server:${{ env.TAG }}-amd64

      # Build and push ARM64 (Raspberry) image
      - name: Build and Push Raspberry (ARM64) Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            rafaelprimeiro/pz-server:${{ env.TAG }}-arm64
            rafaelprimeiro/pz-server:latest
